### ISSUE TITLE
Skrive Forprosjektrapport

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#1]
Dere skal lage en plan for arbeidet som skal legges ut på gruppens hjemmeområde, under /forprosjekt.html. Her forventes kun enkel HTML og CSS; men med kvalitetskrav som ellers.

**Comment by matiashf** [comment]
Vi har satt opp saker i github og lagt inn milestones. Møtes igjen imorgen.

**Comment by matiashf** [comment]
Huske: WCAG (tilgjengelighet) og responsivt design (mobil)

**Comment by matiashf** [comment]
Vi har begynt på rapporten. Sebastian og Haakon hvorfor vi har valgt Git/Github og fordeling av arbeidsoppgaver.
Jeg og Maria skriver om use-cases og prototype, samt tegner skisser.

Oppgaver videre:
Haakon: milepælsplan
Sebastian: Liste over hvilke teknologier
Matias: Beskrivelse av arbeidsmetoden

CSS tar vi i felleskap på tirsdag.

**Comment by zuza92** [comment]
Jeg har skrevet enkel milepælsplan

**Comment by matiashf** [comment]
Fristen er midnatt, altså om litt under elleve timer. Denne må være ferdig idag. Jeg jobber med dette i forelesning, og kommer til å sitte med dette på kvelden fra halv sju og utover.

**Comment by matiashf** [comment]
Sebastian tar over denne nå.

Sebastian: Her er det jeg vi du skal gjøre.
1. Les gjennom de to tekstene og se at de gir mening. Tenk deg at du ikke vet noe om prosjektet. Er det noe du savner? Rett eventuelle språkfeil med en gang.
2. Sammenlign begge dokumentene med oppgaveteksten vi har fått. Stemmer det overens? Hva mangler?
3. Gå igjennom sjekklisten i kravspec'en og test det du synes er relevant for begge dokumentene. Hvis noe i sjekklisten er uklart, gi meg (Matias) beskjed.

**Comment by sebasho** [comment]
Har gått igjennom begge rapportene nå, det ser veldig bra ut! VI ER SÅ FLINKE ALTSÅ.
