### ISSUE TITLE
Valg av teknologi

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#10]
Det skal dokumenteres hvilke teknologier vi har vurdert å bruke og hvilke vi faktisk har valgt å bruke og begrunnelse for valgene.

**Comment by matiashf** [comment]
Sjekk ut http://getbootstrap.com/

Er dette interessant?

**Comment by sebasho** [comment]
Har lagt til teknologilisten i forprosjekt oppgaven. Har også funnet ut at bootstrap ikke er så lurt å bruke, mest fordi det blir mindre læring, og mindre jobbing for oss.

**Comment by zuza92** [comment]
Dette er vi nå ferdig med.
