### ISSUE TITLE
Ønskeliste: Spillelister med treningsmusikk (spotify)

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#13]
Denne saken gjøres kun dersom vi ligger godt an i forhold til planen.

Legg til spotify-widget i en eller flere av inspirasjonssidene, slik som beskrevet her: https://developer.spotify.com/technologies/widgets/spotify-play-button/

**Comment by zuza92** [comment]
Jobber med denne nå. Tester på løpesiden

**Comment by sebasho** [comment]
Løping, fotball, salsa, langrenn, kubb og yoga har spillelister fra spotify på siden! Haakon gjorde dette.

**Comment by matiashf** [comment]
Bra! Gjenstår eventuelt layout og responsiv visning.
