### ISSUE TITLE
Gjennomgå sjekklisten for forprosjektrapport.html og kravspec.html

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#16]
Maria: Se på sjekklisten i kravspec.html. For hvert av punktene, sjekk kravspec.html og forprosjektrapport.html. Noter ned her hvilke punkter som har mangler. Hvis du lurer på noe, spør meg (Matias).

Målet med dette er at du skal bli bedre kjent med kravspec'en, trene på å bruke github, og at vi får "testet" sjekklisten og forprosjektfilene.

Skriv også ned her tanker du gjør deg underveis, og når du begynner eller slutter med saken (f.eks "Jobber med denne saken nå").

**Comment by MariaSa** [comment]
Notater jeg skrev ned underveis (kommenter/kom med forbedringer):

Visuelt: 
- Ett bilde i hver eneste inspirasjonsside (lik størrelse, noenlunde lik kvalitet)
- Bilde til venstre
- Tekst til høyre
- Like lange avsnitt i hver eneste inspirasjonsside. Hvis vi kommer frem til at noen av oss har skrevet lengre senere må vi eventuelt forkorte/adde på mer tekst. Greia er at det skal se proft ut. 

Søkefunksjon: 
- Droppes med grunn: Vi fokuserer på god navigering istedenfor

Navigasjonsmeny:
- Enkel, oversiktlig
- Tilpasset slik at folk kan gå rett til en idrett de liker eller vil lese mer om 
  (ikke sikkert bare latinger/utrente/de med lite peil som klikker seg inn til siden vår)

Inspirasjonssider:
- Skulle vi ha med quotes fra berømte mennesker innad de ulike idrettene?
- Hvis vi har tid til overs tenkte jeg vi kunne redigere litt på bilder og slikt via et bilderedigeringsprogram til
  inspirasjonssidene våre. Hva syns dere om dette?
  Men dette tenkte jeg vi da kunne ta helt på slutten. Noen som har peil med Photoshop osv? Vi bruker da
  selvfølgelig bilder frie for opphavsrett slik Matias sa. Men kan eventuelt adde på f.eks quotes og sitere.
  For inspirasjon.

**Comment by matiashf** [comment]
Har lagt listen med forslag inn i forskjellige issues.

**Comment by MariaSa** [comment]
Fjernet dobbel kode + rettet på link: "Valider som css3" til engelsk

**Comment by MariaSa** [comment]
Gått gjennom sjekkliste for kravspesifikasjon. Den er i orden.

**Comment by MariaSa** [comment]
Gått gjennom sjekkliste for forprosjektrapporten. I orden.
