### ISSUE TITLE
forbedre mobilversjonen av forprosjektsidene

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#17]
Vi må lære å lage responsivt design, og kan bruke forprosjektsidene til å teste dette.
1. Ta en titt på denne: http://webdesignledger.com/infographics/responsive-design-getting-it-right
2. Få forprosjektsidene til å vises uten zoom på mobil. Jeg tror det må legges til en meta-tag i html-filene.
3. Juster css slik at bilder vises i full bredde. Kanskje må margin og padding på html og body settes til null?

Post fortløpende på github om hva som blir gjort.

**Comment by zuza92** [comment]
Har lagt til meta-tag for zoom på mobil. Gjenstår litt på kantene

**Comment by zuza92** [comment]
punkt nr 3 var en dårlig ide. oppgaven er nå utført
