### ISSUE TITLE
Inspirasjonsside: Hip-hop

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#20]

**Comment by MariaSa** [comment]
Startet å jobbe med den. Ble ikke ferdig.

**Comment by MariaSa** [comment]
Jobber med denne nå.

**Comment by MariaSa** [comment]
Jobber med denne nå.

**Comment by MariaSa** [comment]
Ferdig med denne. Skal forsøke å finne bedre bilde etter hvert.
