### ISSUE TITLE
Ønskeliste: Sitater på inspirasjonssidene

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#25]
Maria skrev: Skulle vi ha med quotes fra berømte mennesker innad de ulike idrettene?

Dette gjør vi bare hvis vi har tid.

**Comment by MariaSa** [comment]
Tar det for enkelte inspirasjonssider som det tar kort tid å finne quotes til. Bruker blockout

**Comment by MariaSa** [comment]
Ferdig med quotes for alle inspo-sidene

**Comment by matiashf** [comment]
Bra! :+1:
