### ISSUE TITLE
Kvalitetssikre inspirasjonssidene

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#26]
Gjennomgå bilder og tekst på inspirasjonssidene:
- Ett bilde i hver eneste inspirasjonsside (lik størrelse, noenlunde lik kvalitet)
- Like lange avsnitt i hver eneste inspirasjonsside. Hvis vi kommer frem til at noen av oss har skrevet lengre senere må vi eventuelt forkorte/adde på mer tekst. Greia er at det skal se proft ut.

**Comment by MariaSa** [comment]
Skulle vi ha utstyrsliste til hver enkel idrett? 
Skal vi da ha bilder av utstyret eller bare oversikt med utstyr vedkommende trenger for å komme i gang?

**Comment by MariaSa** [comment]
Dropper utstyrsliste, bilder har egen issue. Sjekker opp med avsnitt og lengde på tekst.

**Comment by MariaSa** [comment]
Jobber med denne nå. Så at det var lagt til link http://ux.stackexchange.com/questions/3618/ideal-column-width-for-paragraphs-online på vår kravspec. Sjekker opp.
