### ISSUE TITLE
Siden for å sjekke kontrastforhold fungerer ikke 

### ISSUE THREAD

**Issue by MariaSa** [matiashf/webprosjekt-gruppe31#27]
http://student.cs.hioa.no/~s193364/webprosjekt-gruppe31/kravspec.html

**Comment by matiashf** [comment]
http://snook.ca/technical/colour_contrast/colour.html

**Comment by matiashf** [comment]
Vi tester ikke åpenbart leselig tekst (svart på hvitt)
