### ISSUE TITLE
Inspirasjonsside: Fotball

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#3]

**Comment by zuza92** [comment]
Begynner å jobbe med denne nå.

**Comment by zuza92** [comment]
Lagt til informasjon om fotball, link til Osi fotball og bilde. (bildet kommer ikke opp enda)

**Comment by matiashf** [comment]
Tar en titt på denne nå.

**Comment by matiashf** [comment]
Det gjenstår å gjennomgå sjekklisten og skrive ned avvik her.
