### ISSUE TITLE
Easter egg

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#31]
Som i oblig 2 skal dere ha med et easter egg i oppgaven. 
- Når brukeren gjør en helt bestemt handling, eller rekkefølge av handlinger, skal dere bruke javascript til å vise noe skjult innhold. Dere bestemmer innholdet selv!
- Dere bestemmer selv hva brukeren skal gjøre for å få frem det skjulte innholdet, men det må være noe man ikke lett kan gjette seg til
- Dere skal lage en enkel tekstfil "4easterbunny.txt" i samme mappe som forsiden din, der det står en tekst som beskriver hvordan man finner easter-egget.
- Vær kreativ - prøv å gjør noe gøy!

**Comment by matiashf** [comment]
http://electrasinclair.deviantart.com/art/You-Make-My-Heart-Fly-75534762

http://www.hioa.no/Person?id=alfreb

**Comment by matiashf** [comment]
Spec:
Nå man klikker 10 ganger på toggle-linja over inspirasjonstesten, så skal et bilde av alfred på hjertebakgrunn vises.

**Comment by sebasho** [comment]
Haakon jobber også med denne, sammen med meg.

**Comment by sebasho** [comment]
Jobber med denne nå

**Comment by sebasho** [comment]
Ser ut til at vi må bruke html, jquery eller javascript. Har sett på metodene OneMouseDown, onclik eller count. LItt usikker på hva vi skal bruke, tester forskjellige ting!

**Comment by matiashf** [comment]
Du kan "hekte deg på" javascript-koden som allerede er skrevet.

i var Funnel = function(template) {...} initialiserer du en tellevariabel.

I Funnel.prototype.toggle = function(event) inkrementerer du tellere, og hvis den er stor nok, kjører easter egg.

Easter-egg koden kan du godt implementere som en egen function:
Funnel.prototype.toggle = function() {...}

**Comment by sebasho** [comment]
Laget den branchen!

**Comment by matiashf** [comment]
Tar denne nå.

**Comment by matiashf** [comment]
Har støtt på en bug i funnel-koden. Debugger.

**Comment by matiashf** [comment]
Fant feilen.
