### ISSUE TITLE
Bytt ut bilder med nedskalerte varianter

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#38]
Påbegynt i #36.

Jeg har lagt til en makefile som nedskalerer bildene for forskjellige pikselbredder. Det gjenstår å skrive javascript- og php-kode som bytter ut img src-attributtene _før_ de "store" bildene begynner å laste.

**Comment by matiashf** [comment]
Jobber med denne nå.

**Comment by matiashf** [comment]
Jeg er ferdig med denne nå, men det gjenstår å gå igjennom forsiden og gjøre om src-taggene til optimized_image()-kall.

Sebastian: Kan du gjøre dette? Spør meg hvis du lurer på noe.

**Comment by matiashf** [comment]
Rettelse: Det gjenstår å gå igjennom hver enkelt _inspirasjonsside_.

**Comment by sebasho** [comment]
Ser på denne nå!

**Comment by matiashf** [comment]
Husk å legge til alt-tagger.

**Comment by sebasho** [comment]
Jobber med denne nå

**Comment by sebasho** [comment]
Ferdig med denne for i dag.

**Comment by sebasho** [comment]
Når jeg skulle legge til teksten i "alt" så ble ikke bildet endret til den størrelsen den skulle være i..

**Comment by sebasho** [comment]
Det ser ut til at denne oppgaven er ferdig, da gjenstår det å endre størrelsen på bildene i css.
