### ISSUE TITLE
Bytt ut bilder slik at alle bilder er i samme størrelsesforhold

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#39]
Noen av bildene på aktivitetssitdene er i størrelsesforhold som gjør at de ikke fungerer sammen på forsiden. Vi må finne alternative bilder som har riktig størrelsesforhold.
1. Se over bildene på forsiden og bestem hvilke som ikke passer inn.
2. Finn hvilket størrelsesforhold vi skal bruke.
3. Bytt ut bilder.

**Comment by sebasho** [comment]
JObber med dette nå

**Comment by sebasho** [comment]
Ser meg ferdig med denne for i dag

**Comment by sebasho** [comment]
Alle bildene skal nå passe inn. Det eneste som mangler å gjøre nå er å finne ut hvilken størrelse vi skal bruke i CSS.

**Comment by matiashf** [comment]
Jeg forsto ikke helt hva du mente. Kan du utdype?

**Comment by sebasho** [comment]
Bildet var avlangt.. Så det matchet ikke de andre bildene så bra..

**Comment by matiashf** [comment]
Denne utgår.
