### ISSUE TITLE
Enkelt design for inspirasjonssider

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#4]
Legg pålayout og eventuelt enkelt design på inspirasjonssidene

Desktop-størrelse: Bilde til venstre, Tekst til høyre
Mobil: Bilde over tekst

Hva mer skal med?

**Comment by sebasho** [comment]
Begynner med denne nå!

**Comment by sebasho** [comment]
Ferdig med dette for i dag

**Comment by sebasho** [comment]
Jobber litt med denne nå

**Comment by sebasho** [comment]
Er ferdig med denne !
