### ISSUE TITLE
Legge til støtte for keybord-navigering på inspirasjonstesten

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#42]

**Comment by sebasho** [comment]
Begynner med denne nå!

**Comment by sebasho** [comment]
Kan dette være aktuelt? https://developer.mozilla.org/en-US/docs/Accessibility/Keyboard-navigable_JavaScript_widgets

**Comment by matiashf** [comment]
Ja, det ser ut som en god ressurs. Sånn jeg leser den kan vi sette tabindex="0" på alle <label>-elementene, og teste navigering med tab og enter.

**Comment by sebasho** [comment]
Tester ut dette nå!

**Comment by sebasho** [comment]
Funket dårlig med tabindex="0"...
