### ISSUE TITLE
Implementere delings-lenker

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#49]
Deling til facebook og twitter må implementeres.

**Comment by matiashf** [comment]
Ta en titt på denne, Sebastian. Rediger i common.php og test med forsiden.

**Comment by sebasho** [comment]
JObber med denne nå!

**Comment by sebasho** [comment]
Fant ut hvordan man gjør det. http://blog.socialsourcecommons.org/2011/03/creating-share-this-on-facebooktwitter-links/ Det er også mulig å lage Like pages på twitter og facebook, hvis vi vil det da!

**Comment by sebasho** [comment]
Det går an å dele, men det ser litt rart ut på facebook i allefall..

**Comment by sebasho** [comment]
Ferdig med denne, eventuelt se på det sammen med Matias senere i dag.

**Comment by matiashf** [comment]
Gjenstår for meg å teste.

**Comment by matiashf** [comment]
Ser på denne nå.

**Comment by matiashf** [comment]
Lenkene deler bare forsiden, ikke nåværende side.

**Comment by matiashf** [comment]
Opprettet facebook-app med id 319645501512056.

**Comment by matiashf** [comment]
Dette fungerer, men ikke på localhost.
