### ISSUE TITLE
Gjør kostholdskarusellen interaktiv

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#50]

**Comment by matiashf** [comment]
Jobber med denne nå.

**Comment by matiashf** [comment]
Denne er ferdig implementert, dog ikke med samme animasjon som i skissene.

**Comment by sebasho** [comment]
Fant feil i kostholdskarusellen! Hvis du tester med Internett Explorer, så kommer den opp speilvendt når du tryker videre, knappen blir nesten borte også. Dette skjer hvert andre trykk! Håper dette gav noen mening da:P
