### ISSUE TITLE
Endre overskrifter

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#55]
- Unødvendige overskrifter må skjules i css, men vises av blinde.
- Fjernene «inspirasjonsside: » fra overskriften i inspirasjonssidene.

**Comment by sebasho** [comment]
På Innspirasjonstesten bør vi skrive om overskriften til: Hvilken aktivitet passer for deg? eller noe lignende, brukertestet litt i går. Det var vanskelig å skjønne hva den testen gjorde.
Det var også vanskelig å skjønne at du kunne trykke på inspirasjonsidene..
