### ISSUE TITLE
Sluttrapporten

### ISSUE THREAD

**Issue by matiashf** [matiashf/webprosjekt-gruppe31#57]

**Comment by matiashf** [comment]
Mine notater fra forelesningen:

Regner med at rapporten teller 20%.
Det er lov å kopiere fra forprosjektrapporten til sluttrapporten.
Innhold i sluttrapport:
• Detaljert beskrivelse av hva som er implementert, sett i sammenheng med forprosjektrapporten.
• En tidslinje som viser hva som ble gjennomført når, sett i sammenheng med milepelsplanen i forprosjektet.
• Evaluering av
∘ Metoder
∘ Verktøy
∘ Teknologier
∘ Hva fungerte? Hva fungerte ikke. Hva brukte dere mest tid på? Var dette slik dere hadde trodd?
• Refleksjon rundt prosjektgjennomføringen. Hvilke utfordringer møtte dere? Var det timeplaner og estimater som sprakk? Hvis ikke, la dere kanskje ambisjonsnivået for lavt? Hadde dere diskusjoner og uenigheter? (Refleksjonsnotatet bør være et vedlegg til rapporten.)

Lengden på rapporten kan være mer eller mindre enn 8-10 sider. Altså må man vurdere selv hvor mye arbeid som skal legges inn rapporten!

Alfred vurderer det tekniske, Thor ser på prosjektrapporten.

Thor sitter på PS322 eller kan nås på e-post. Avtal helst møte på e-post, men det er lov å stikke innom.

I Rapporten: Har vi tatt hensyn til universell utforming? Trenger ikke være mye tekst (minimum en setning eller to).

Hvordan kan vi få brukerne til å bruke vårt nye system? Hvilke ting er viktigere enn andre i opplæring og aksptansefasen av et nytt IS?

**Comment by zuza92** [comment]
Begynner å skrive om evaluering...

**Comment by sebasho** [comment]
Betyr det alle tre?

**Comment by zuza92** [comment]
Begynner på Metoder nå.. du kan ta verktøy eller eller hva fungerte/fungerte ikke? hvis ikke begynner jeg på alle nå og ser hvor langt jeg kommer..

**Comment by sebasho** [comment]
Da tar jeg verktøy!

**Comment by sebasho** [comment]
jobber med implementering nå!

**Comment by sebasho** [comment]
Implementering ferdig

**Comment by sebasho** [comment]
Jobber med Universell utforming nå
